//! Elasticsearch service provider — single-node, security disabled for tests.
//!
//! The same container config works for ES 7 and 8: `discovery.type=single-node`
//! turns off the production bootstrap checks, and `xpack.security.enabled=false`
//! (valid in both majors) keeps HTTP plain so the app and the runner can reach
//! it without TLS/credentials. The 7-vs-8 difference lives in the *template*
//! format (handled by the check/runner and generated by Claude), not here.

use std::collections::BTreeMap;

use anyhow::{anyhow, Result};
use serde::Serialize;

use super::{ComposeService, Healthcheck, ServiceProvider};
use crate::spec::{ServiceDecl, ServiceKind};

pub struct Elastic;

#[derive(Serialize)]
struct ElasticBody {
    image: String,
    environment: BTreeMap<String, String>,
    ports: Vec<String>,
    networks: Vec<String>,
    healthcheck: Healthcheck,
}

impl ServiceProvider for Elastic {
    fn kind(&self) -> ServiceKind {
        ServiceKind::Elastic
    }

    fn compose_service(&self, decl: &ServiceDecl, _assigned: Option<u16>) -> Result<ComposeService> {
        let mut env = BTreeMap::new();
        env.insert("discovery.type".into(), "single-node".into());
        // Disable security so the app + runner talk plain HTTP (works on 7 & 8).
        env.insert("xpack.security.enabled".into(), "false".into());
        // Keep the JVM small; the host's vm.max_map_count check is skipped in
        // single-node mode.
        env.insert("ES_JAVA_OPTS".into(), "-Xms512m -Xmx512m".into());

        let body = ElasticBody {
            image: decl.image.clone(),
            environment: env,
            ports: vec!["9200".to_string()],
            networks: vec!["noworries".to_string()],
            healthcheck: Healthcheck {
                test: vec![
                    "CMD-SHELL".to_string(),
                    "curl -s -f http://localhost:9200/_cluster/health || exit 1".to_string(),
                ],
                interval: "5s".to_string(),
                timeout: "5s".to_string(),
                retries: 30,
                start_period: "20s".to_string(),
            },
        };

        Ok(ComposeService {
            name: "elastic".to_string(),
            kind: ServiceKind::Elastic,
            container_port: 9200,
            has_healthcheck: true,
            host_port: None,
            body: serde_yaml::to_value(body).map_err(|e| anyhow!(e))?,
        })
    }
}
