//! Generates the ephemeral `.noworries/compose.test.yml` from the declared
//! services by asking each service's provider for its compose fragment.

use std::collections::BTreeMap;

use anyhow::{anyhow, Result};
use serde::Serialize;

use crate::services::{provider_for, ComposeService};
use crate::spec::ServiceDecl;

pub struct GeneratedCompose {
    pub project_name: String,
    pub yaml: String,
    pub services: Vec<ComposeService>,
}

#[derive(Serialize)]
struct Network {
    name: String,
    driver: String,
}

#[derive(Serialize)]
struct Networks {
    noworries: Network,
}

#[derive(Serialize)]
struct ComposeDoc {
    name: String,
    networks: Networks,
    services: BTreeMap<String, serde_yaml::Value>,
}

pub fn generate(decls: &[ServiceDecl], run_id: &str) -> Result<GeneratedCompose> {
    let project = format!("noworries-{run_id}");
    let net = format!("{project}_net");

    let mut services = Vec::new();
    let mut map: BTreeMap<String, serde_yaml::Value> = BTreeMap::new();
    for decl in decls {
        let provider = provider_for(decl.kind).ok_or_else(|| {
            anyhow!(
                "compose generation for {} is not implemented yet in this phase. \
                 Remove it from noworries.yml.",
                decl.kind.as_str()
            )
        })?;
        // Services whose advertised address must be known up front (Kafka) get a
        // free host port picked now; others use a Docker-assigned random port.
        let assigned = if provider.needs_fixed_host_port() {
            Some(crate::app::pick_free_port()?)
        } else {
            None
        };
        let svc = provider.compose_service(decl, assigned)?;
        map.insert(svc.name.clone(), svc.body.clone());
        services.push(svc);
    }

    let doc = ComposeDoc {
        name: project.clone(),
        networks: Networks {
            noworries: Network {
                name: net,
                driver: "bridge".to_string(),
            },
        },
        services: map,
    };

    let header = format!(
        "# Generated by noworries — do not edit by hand.\n\
         # Ephemeral test infrastructure for project \"{project}\".\n\
         # Recreated each run; torn down with `docker compose down -v`.\n"
    );
    let yaml = format!("{header}{}", serde_yaml::to_string(&doc)?);

    Ok(GeneratedCompose {
        project_name: project,
        yaml,
        services,
    })
}
