//! Generates the ephemeral `.noworries/compose.test.yml` from the declared
//! services by asking each service's provider for its compose fragment.

use std::collections::BTreeMap;

use anyhow::{anyhow, Result};
use serde::Serialize;

use crate::flink;
use crate::services::{provider_for, ComposeService};
use crate::spec::{FlinkSpec, ServiceDecl};

pub struct GeneratedCompose {
    pub project_name: String,
    pub yaml: String,
    pub services: Vec<ComposeService>,
    /// Non-service containers (currently the Flink cluster) that lifecycle must
    /// still wait for and, when `resolve_port` is set, resolve a host port for.
    pub aux: Vec<AuxContainer>,
}

/// A generated container that isn't one of the declared [`ServiceKind`] services
/// but still participates in the run (health-wait and optional port resolution).
pub struct AuxContainer {
    pub name: String,
    /// Container port to resolve a host mapping for, if any.
    pub resolve_port: Option<u16>,
}

#[derive(Serialize)]
struct Network {
    name: String,
    driver: String,
}

#[derive(Serialize)]
struct Networks {
    noworries: Network,
}

#[derive(Serialize)]
struct ComposeDoc {
    name: String,
    networks: Networks,
    services: BTreeMap<String, serde_yaml::Value>,
}

pub fn generate(
    decls: &[ServiceDecl],
    flink_spec: Option<&FlinkSpec>,
    run_id: &str,
) -> Result<GeneratedCompose> {
    let project = format!("noworries-{run_id}");
    let net = format!("{project}_net");

    let mut services = Vec::new();
    let mut map: BTreeMap<String, serde_yaml::Value> = BTreeMap::new();
    for decl in decls {
        let provider = provider_for(decl.kind).ok_or_else(|| {
            anyhow!(
                "compose generation for {} is not implemented yet in this phase. \
                 Remove it from noworries.yml.",
                decl.kind.as_str()
            )
        })?;
        // Services whose advertised address must be known up front (Kafka) get a
        // free host port picked now; others use a Docker-assigned random port.
        let assigned = if provider.needs_fixed_host_port() {
            Some(crate::app::pick_free_port()?)
        } else {
            None
        };
        let svc = provider.compose_service(decl, assigned)?;
        map.insert(svc.name.clone(), svc.body.clone());
        services.push(svc);
    }

    // Flink session cluster (jobmanager + taskmanager), if this run tests a job.
    let mut aux = Vec::new();
    if let Some(fs) = flink_spec {
        let kinds: Vec<_> = decls.iter().map(|d| d.kind).collect();
        for c in flink::cluster_services(fs, &kinds)? {
            map.insert(c.name.clone(), c.body);
            aux.push(AuxContainer {
                name: c.name,
                resolve_port: c.resolve_port,
            });
        }
    }

    let doc = ComposeDoc {
        name: project.clone(),
        networks: Networks {
            noworries: Network {
                name: net,
                driver: "bridge".to_string(),
            },
        },
        services: map,
    };

    let header = format!(
        "# Generated by noworries — do not edit by hand.\n\
         # Ephemeral test infrastructure for project \"{project}\".\n\
         # Recreated each run; torn down with `docker compose down -v`.\n"
    );
    let yaml = format!("{header}{}", serde_yaml::to_string(&doc)?);

    Ok(GeneratedCompose {
        project_name: project,
        yaml,
        services,
        aux,
    })
}
